import type { Question } from "./types";

export const PAID_QUESTIONS: Question[] = [
  // ─── B1: Civil Documents ─────────────────────────────────────────────────────
  {
    id: "P-B1-01",
    section: "B1",
    type: "yesno",
    question: "Do you have a valid passport?",
    storesAs: "has_passport",
    required: true,
    note: "Your passport must be valid for at least 6 months beyond your intended stay.",
  },
  {
    id: "P-B1-01A",
    section: "B1",
    type: "single",
    question: "Can you obtain a passport?",
    subtitle: "A valid passport is required for any international travel.",
    storesAs: "can_obtain_passport",
    required: true,
    options: [
      { label: "Yes, I can get one", value: "yes" },
      { label: "No, I cannot", value: "no" },
      { label: "Not sure", value: "unsure" },
    ],
    showIf: (answers) => answers.has_passport === "no",
  },
  {
    id: "P-B1-02",
    section: "B1",
    type: "single",
    question: "How long is your passport valid?",
    storesAs: "passport_validity",
    required: true,
    options: [
      { label: "Less than 6 months", value: "under_6m" },
      { label: "6 – 12 months", value: "6_12m" },
      { label: "More than 12 months", value: "over_12m" },
      { label: "Not sure", value: "unsure" },
    ],
    showIf: (answers) => answers.has_passport === "yes",
  },
  {
    id: "P-B1-03",
    section: "B1",
    type: "yesno",
    question: "Do you have any previous passports?",
    storesAs: "has_previous_passports",
    required: true,
  },
  {
    id: "P-B1-04",
    section: "B1",
    type: "yesno",
    question: "Do you have a valid National ID card?",
    storesAs: "has_national_id",
    required: true,
  },
  {
    id: "P-B1-04A",
    section: "B1",
    type: "single",
    question: "Can you obtain a National ID?",
    storesAs: "can_obtain_national_id",
    required: true,
    options: [
      { label: "Yes", value: "yes" },
      { label: "No", value: "no" },
      { label: "Not sure", value: "unsure" },
    ],
    showIf: (answers) => answers.has_national_id === "no",
  },
  {
    id: "P-B1-05",
    section: "B1",
    type: "yesno",
    question: "Do you have a birth certificate?",
    storesAs: "has_birth_certificate",
    required: true,
  },
  {
    id: "P-B1-05A",
    section: "B1",
    type: "single",
    question: "Can you obtain a birth certificate?",
    storesAs: "can_obtain_birth_cert",
    required: true,
    options: [
      { label: "Yes", value: "yes" },
      { label: "No", value: "no" },
      { label: "Not sure", value: "unsure" },
    ],
    showIf: (answers) => answers.has_birth_certificate === "no",
  },
  {
    id: "P-B1-06",
    section: "B1",
    type: "single",
    question: "Do you have an origin or state of origin certificate?",
    storesAs: "has_origin_certificate",
    required: true,
    options: [
      { label: "Yes", value: "yes" },
      { label: "No", value: "no" },
      { label: "Not applicable", value: "na" },
    ],
  },
  {
    id: "P-B1-07",
    section: "B1",
    type: "single",
    question: "Do you have a police clearance certificate?",
    storesAs: "has_police_clearance",
    required: true,
    options: [
      { label: "Yes", value: "yes" },
      { label: "No, but I can obtain one", value: "can_obtain" },
      { label: "No, and I cannot obtain one", value: "no" },
    ],
  },
  {
    id: "P-B1-08",
    section: "B1",
    type: "yesno",
    question: "Are your documents in English or officially translated?",
    subtitle: "Most Nordic countries require documents in English or a Nordic language.",
    storesAs: "docs_in_english",
    required: true,
  },

  // ─── B2: Financial & Sponsorship ─────────────────────────────────────────────
  {
    id: "P-B2-01",
    section: "B2",
    type: "single",
    question: "Can you show proof of sufficient funds for your trip?",
    subtitle: "This is one of the most important factors in any visa decision.",
    storesAs: "has_proof_of_funds",
    required: true,
    options: [
      { label: "Yes", value: "yes" },
      { label: "No", value: "no" },
      { label: "Not sure what counts", value: "unsure" },
    ],
  },
  {
    id: "P-B2-02",
    section: "B2",
    type: "multi",
    question: "Which financial documents do you have?",
    subtitle: "Select all that apply.",
    storesAs: "financial_proof_available",
    required: false,
    options: [
      { label: "Bank statement (3+ months)", value: "bank_statement" },
      { label: "Salary slips", value: "salary_slips" },
      { label: "Sponsorship letter", value: "sponsorship_letter" },
      { label: "Scholarship award letter", value: "scholarship" },
      { label: "Business income proof", value: "business_income" },
    ],
  },
  {
    id: "P-B2-03",
    section: "B2",
    type: "multi",
    question: "Do you own any significant assets?",
    storesAs: "assets_owned",
    required: false,
    options: [
      { label: "Land or property", value: "land_property" },
      { label: "Business", value: "business" },
      { label: "Stocks or investments", value: "stocks" },
      { label: "None of the above", value: "none" },
    ],
  },
  {
    id: "P-B2-04",
    section: "B2",
    type: "single",
    question: "Who will be paying for your trip?",
    storesAs: "who_pays",
    required: true,
    options: [
      { label: "Myself", value: "self" },
      { label: "A family member", value: "family" },
      { label: "My employer", value: "employer" },
      { label: "An organisation / institution", value: "organisation" },
      { label: "I don't know yet", value: "unknown" },
    ],
  },
  {
    id: "P-B2-04A",
    section: "B2",
    type: "single",
    question: "What is your relationship to your sponsor?",
    storesAs: "sponsor_relationship",
    required: true,
    options: [
      { label: "Parent", value: "parent" },
      { label: "Spouse or partner", value: "spouse" },
      { label: "Sibling", value: "sibling" },
      { label: "Other relative", value: "other_relative" },
    ],
    showIf: (answers) => answers.who_pays === "family",
  },
  {
    id: "P-B2-05",
    section: "B2",
    type: "single",
    question: "Can your sponsor prove their income?",
    storesAs: "sponsor_can_prove_income",
    required: false,
    options: [
      { label: "Yes", value: "yes" },
      { label: "No", value: "no" },
      { label: "Not sure", value: "unsure" },
    ],
    showIf: (answers) => answers.who_pays !== "self",
  },
  {
    id: "P-B2-06",
    section: "B2",
    type: "single",
    question: "Is your sponsor based in the destination country?",
    storesAs: "sponsor_in_destination",
    required: false,
    options: [
      { label: "Yes", value: "yes" },
      { label: "No", value: "no" },
      { label: "Not sure", value: "unsure" },
    ],
    showIf: (answers) => answers.who_pays !== "self",
  },

  // ─── B3: Education ────────────────────────────────────────────────────────────
  {
    id: "P-B3-01",
    section: "B3",
    type: "single",
    question: "What is your highest level of education?",
    subtitle: "This section also helps identify alternative study-based visa routes.",
    storesAs: "highest_education",
    required: true,
    options: [
      { label: "Primary school", value: "primary" },
      { label: "Secondary / High school", value: "secondary" },
      { label: "Diploma or certificate", value: "diploma" },
      { label: "Bachelor's degree", value: "bachelor" },
      { label: "Master's degree", value: "masters" },
      { label: "PhD or Doctorate", value: "phd" },
      { label: "No formal education", value: "none" },
    ],
  },
  {
    id: "P-B3-02",
    section: "B3",
    type: "yesno",
    question: "Are you currently enrolled in an educational institution?",
    storesAs: "currently_enrolled",
    required: true,
  },
  {
    id: "P-B3-02A-name",
    section: "B3",
    type: "text",
    question: "What is the name of your institution?",
    placeholder: "e.g. University of Lagos",
    storesAs: "current_institution_name",
    required: false,
    showIf: (answers) => answers.currently_enrolled === "yes",
  },
  {
    id: "P-B3-02A-country",
    section: "B3",
    type: "text",
    question: "Which country is your institution in?",
    placeholder: "e.g. Nigeria",
    storesAs: "current_institution_country",
    required: false,
    showIf: (answers) => answers.currently_enrolled === "yes",
  },
  {
    id: "P-B3-03",
    section: "B3",
    type: "single",
    question: "Do you have an admission or acceptance letter?",
    storesAs: "has_admission_letter",
    required: false,
    options: [
      { label: "Yes", value: "yes" },
      { label: "No, but it's in progress", value: "in_progress" },
      { label: "No", value: "no" },
    ],
  },
  {
    id: "P-B3-04",
    section: "B3",
    type: "single",
    question: "Have you applied for any scholarships?",
    storesAs: "scholarship_status",
    required: false,
    options: [
      { label: "Yes, I have one", value: "yes" },
      { label: "Applied and awaiting result", value: "applied" },
      { label: "Planning to apply", value: "planning" },
      { label: "No", value: "no" },
    ],
  },
  {
    id: "P-B3-05",
    section: "B3",
    type: "multi",
    question: "Which academic documents do you have?",
    storesAs: "academic_documents",
    required: false,
    options: [
      { label: "Degree certificates", value: "certificates" },
      { label: "Academic transcripts", value: "transcripts" },
      { label: "Language test results (IELTS / Duolingo)", value: "language_test" },
      { label: "None yet", value: "none" },
    ],
  },

  // ─── B4: Employment / Business ────────────────────────────────────────────────
  {
    id: "P-B4-01",
    section: "B4",
    type: "single",
    question: "What is your current employment status?",
    subtitle: "This section also identifies alternative work-based routes for you.",
    storesAs: "employment_status",
    required: true,
    options: [
      { label: "Employed (full-time or part-time)", value: "employed" },
      { label: "Self-employed", value: "self_employed" },
      { label: "Freelancer", value: "freelancer" },
      { label: "Student", value: "student" },
      { label: "Not currently working", value: "not_working" },
    ],
  },
  {
    id: "P-B4-02",
    section: "B4",
    type: "text",
    question: "What is your job title?",
    placeholder: "e.g. Software Engineer",
    storesAs: "job_title",
    required: false,
    showIf: (answers) => answers.employment_status === "employed",
  },
  {
    id: "P-B4-03",
    section: "B4",
    type: "text",
    question: "What is your employer's company name?",
    placeholder: "e.g. Access Bank",
    storesAs: "employer_name",
    required: false,
    showIf: (answers) => answers.employment_status === "employed",
  },
  {
    id: "P-B4-04",
    section: "B4",
    type: "single",
    question: "How long have you been employed there?",
    storesAs: "employment_duration",
    required: false,
    options: [
      { label: "Less than 6 months", value: "under_6m" },
      { label: "6 – 12 months", value: "6_12m" },
      { label: "1 – 3 years", value: "1_3y" },
      { label: "More than 3 years", value: "3y_plus" },
    ],
    showIf: (answers) => answers.employment_status === "employed",
  },
  {
    id: "P-B4-05",
    section: "B4",
    type: "text",
    question: "What industry or type of work do you do?",
    placeholder: "e.g. Technology, Healthcare, Agriculture",
    storesAs: "industry",
    required: false,
    showIf: (answers) => answers.employment_status !== "not_working",
  },
  {
    id: "P-B4-06",
    section: "B4",
    type: "yesno",
    question: "Do you have a registered business?",
    storesAs: "has_registered_business",
    required: false,
    showIf: (answers) =>
      answers.employment_status === "self_employed" ||
      answers.employment_status === "freelancer",
  },
  {
    id: "P-B4-07",
    section: "B4",
    type: "yesno",
    question: "Do you work remotely, or are you planning to?",
    storesAs: "works_remotely",
    required: false,
    showIf: (answers) =>
      answers.employment_status === "self_employed" ||
      answers.employment_status === "freelancer",
  },
  {
    id: "P-B4-08",
    section: "B4",
    type: "multi",
    question: "Which employment documents do you have?",
    storesAs: "employment_docs",
    required: false,
    options: [
      { label: "Employment contract", value: "employment_contract" },
      { label: "Job offer letter", value: "job_offer" },
      { label: "Client contracts (freelance)", value: "client_contracts" },
      { label: "Business registration certificate", value: "business_reg" },
      { label: "Proof of income / payslips", value: "proof_of_income" },
      { label: "None yet", value: "none" },
    ],
  },
  {
    id: "P-B4-09",
    section: "B4",
    type: "single",
    question: "How long have you been in your profession overall?",
    storesAs: "years_in_profession",
    required: false,
    options: [
      { label: "Less than 1 year", value: "under_1y" },
      { label: "1 – 3 years", value: "1_3y" },
      { label: "3 – 5 years", value: "3_5y" },
      { label: "More than 5 years", value: "5y_plus" },
    ],
    showIf: (answers) => answers.employment_status !== "not_working",
  },

  // ─── B5: Family & Relationships ───────────────────────────────────────────────
  {
    id: "P-B5-01",
    section: "B5",
    type: "single",
    question: "What is your marital status?",
    storesAs: "marital_status",
    required: true,
    options: [
      { label: "Single", value: "single" },
      { label: "Married", value: "married" },
      { label: "In a registered partnership", value: "registered_partner" },
      { label: "Divorced", value: "divorced" },
      { label: "Widowed", value: "widowed" },
    ],
  },
  {
    id: "P-B5-02",
    section: "B5",
    type: "yesno",
    question: "Do you have a spouse or partner living abroad?",
    storesAs: "partner_abroad",
    required: false,
    showIf: (answers) =>
      answers.marital_status === "married" ||
      answers.marital_status === "registered_partner",
  },
  {
    id: "P-B5-03",
    section: "B5",
    type: "single",
    question: "What type of relationship is it?",
    storesAs: "partner_relationship_type",
    required: false,
    options: [
      { label: "Legal spouse (married)", value: "legal_spouse" },
      { label: "Registered partner", value: "registered_partner" },
      { label: "Fiancé(e)", value: "fiance" },
      { label: "Informal partner", value: "informal" },
    ],
    showIf: (answers) => answers.partner_abroad === "yes",
  },
  {
    id: "P-B5-04",
    section: "B5",
    type: "single",
    question: "What is your partner's legal status in the destination country?",
    storesAs: "partner_legal_status",
    required: false,
    options: [
      { label: "Citizen", value: "citizen" },
      { label: "Permanent resident", value: "permanent_resident" },
      { label: "Temporary resident", value: "temporary_resident" },
      { label: "Not sure", value: "unsure" },
    ],
    showIf: (answers) => answers.partner_abroad === "yes",
  },
  {
    id: "P-B5-05",
    section: "B5",
    type: "multi",
    question: "Which relationship documents do you have?",
    storesAs: "relationship_docs",
    required: false,
    options: [
      { label: "Marriage certificate", value: "marriage_cert" },
      { label: "Birth certificate (joint children)", value: "birth_cert" },
      { label: "Photos and communications history", value: "photos_comms" },
      { label: "None yet", value: "none" },
    ],
    showIf: (answers) => answers.partner_abroad === "yes",
  },
  {
    id: "P-B5-06",
    section: "B5",
    type: "yesno",
    question: "Have you and your partner lived together before?",
    storesAs: "lived_together",
    required: false,
    showIf: (answers) => answers.partner_abroad === "yes",
  },
  {
    id: "P-B5-07",
    section: "B5",
    type: "single",
    question: "How long have you been in this relationship?",
    storesAs: "relationship_duration",
    required: false,
    options: [
      { label: "Less than 1 year", value: "under_1y" },
      { label: "1 - 2 years", value: "1_2y" },
      { label: "2 - 5 years", value: "2_5y" },
      { label: "More than 5 years", value: "5y_plus" },
    ],
    showIf: (answers) => answers.partner_abroad === "yes",
  },
  {
    id: "P-B5-08",
    section: "B5",
    type: "yesno",
    question: "Are you travelling with children?",
    storesAs: "travelling_with_children",
    required: false,
  },
  {
    id: "P-B5-09",
    section: "B5",
    type: "number",
    question: "How many children are travelling with you?",
    storesAs: "number_of_children",
    required: false,
    validation: { min: 1, max: 10 },
    showIf: (answers) => answers.travelling_with_children === "yes",
  },
  {
    id: "P-B5-10",
    section: "B5",
    type: "single",
    question: "Do your children have valid passports?",
    storesAs: "children_have_passports",
    required: false,
    options: [
      { label: "Yes, all of them", value: "yes_all" },
      { label: "Some of them", value: "some" },
      { label: "No", value: "no" },
      { label: "In progress", value: "in_progress" },
    ],
    showIf: (answers) => answers.travelling_with_children === "yes",
  },

  // ─── B6: Travel History & Risk ────────────────────────────────────────────────
  {
    id: "P-B6-01",
    section: "B6",
    type: "yesno",
    question: "Have you ever travelled outside Nigeria?",
    storesAs: "has_travel_history",
    required: true,
  },
  {
    id: "P-B6-02",
    section: "B6",
    type: "multi",
    question: "Which countries have you visited or lived in?",
    subtitle: "Prior travel history to Schengen countries strengthens your application.",
    storesAs: "countries_visited",
    required: false,
    options: [
      { label: "UK", value: "uk" },
      { label: "USA or Canada", value: "usa_canada" },
      { label: "Schengen Area (EU Europe)", value: "schengen" },
      { label: "Other African countries", value: "africa" },
      { label: "UAE or Gulf countries", value: "uae_gulf" },
      { label: "Other", value: "other" },
    ],
    showIf: (answers) => answers.has_travel_history === "yes",
  },
  {
    id: "P-B6-03",
    section: "B6",
    type: "single",
    question: "Have you previously applied for a visa?",
    storesAs: "previous_visa_applications",
    required: true,
    options: [
      { label: "Yes - and it was approved", value: "approved" },
      { label: "Yes - and it was refused", value: "refused" },
      { label: "Yes - I have had both approvals and refusals", value: "both" },
      { label: "No, I've never applied", value: "never" },
    ],
  },
  {
    id: "P-B6-04",
    section: "B6",
    type: "yesno",
    question: "Have you ever overstayed a visa, been deported, or denied entry?",
    subtitle: "This is a significant risk factor in any visa assessment.",
    storesAs: "has_immigration_violations",
    required: true,
  },
  {
    id: "P-B6-05",
    section: "B6",
    type: "single",
    question: "Do you have any criminal record or pending criminal case?",
    subtitle: "Your answer is confidential and only used to assess eligibility.",
    storesAs: "has_criminal_record",
    required: true,
    options: [
      { label: "No", value: "no" },
      { label: "Yes - fully resolved / spent conviction", value: "yes_resolved" },
      { label: "Yes - pending or recent", value: "yes_pending" },
    ],
  },

  // ─── B7: Medical ─────────────────────────────────────────────────────────────
  {
    id: "P-B7-01",
    section: "B7",
    type: "yesno",
    question: "Are you travelling for medical treatment?",
    storesAs: "travelling_for_medical",
    required: true,
  },
  {
    id: "P-B7-02",
    section: "B7",
    type: "single",
    question: "Do you have a medical referral or hospital invitation letter?",
    storesAs: "has_medical_referral",
    required: false,
    options: [
      { label: "Yes", value: "yes" },
      { label: "No, but I can get one", value: "can_obtain" },
      { label: "No", value: "no" },
      { label: "Not sure", value: "unsure" },
    ],
    showIf: (answers) => answers.travelling_for_medical === "yes",
  },
  {
    id: "P-B7-03",
    section: "B7",
    type: "yesno",
    question: "Do you have proof of payment or sponsorship for the treatment?",
    storesAs: "has_medical_payment_proof",
    required: false,
    showIf: (answers) => answers.travelling_for_medical === "yes",
  },
  {
    id: "P-B7-04",
    section: "B7",
    type: "yesno",
    question: "Do you have any health condition that could affect travel or insurance eligibility?",
    subtitle: "This helps us flag any insurance requirements.",
    storesAs: "has_health_condition",
    required: true,
  },

  // ─── B8: Readiness ────────────────────────────────────────────────────────────
  {
    id: "P-B8-01",
    section: "B8",
    type: "multi",
    question: "Which of these documents do you already have?",
    subtitle: "Be honest - this directly shapes your report.",
    storesAs: "documents_ready",
    required: false,
    options: [
      { label: "Valid passport", value: "passport" },
      { label: "Bank statement", value: "bank_statement" },
      { label: "Invitation letter", value: "invitation" },
      { label: "Admission / acceptance letter", value: "admission" },
      { label: "Employment contract", value: "employment_contract" },
      { label: "Sponsorship letter", value: "sponsorship" },
      { label: "Accommodation proof (hotel / host letter)", value: "accommodation" },
      { label: "Travel insurance", value: "travel_insurance" },
      { label: "None yet", value: "none" },
    ],
  },
  {
    id: "P-B8-02",
    section: "B8",
    type: "single",
    question: "How willing are you to gather missing documents?",
    storesAs: "willingness_to_gather_docs",
    required: true,
    options: [
      { label: "Very willing - I'll do what it takes", value: "very_willing" },
      { label: "Willing, depending on difficulty", value: "somewhat_willing" },
      { label: "Not sure", value: "unsure" },
    ],
  },

  // ─── B9: Final Confirmations ─────────────────────────────────────────────────
  {
    id: "P-B9-01",
    section: "B9",
    type: "single",
    question: "Who are you applying with?",
    storesAs: "applying_with",
    required: true,
    options: [
      { label: "Just me (solo)", value: "alone" },
      { label: "Me and my spouse", value: "with_spouse" },
      { label: "Me and my children", value: "with_children" },
      { label: "Me and my whole family", value: "with_family" },
    ],
  },
  {
    id: "P-B9-02",
    section: "B9",
    type: "single",
    question: "What type of report output do you want?",
    storesAs: "desired_output",
    required: true,
    options: [
      { label: "Eligibility result only", value: "eligibility_only" },
      { label: "Result + document checklist", value: "with_checklist" },
      { label: "Result + checklist + improvement steps", value: "with_suggestions" },
      { label: "Everything - full report", value: "full" },
    ],
  },
];

export const PAID_SECTIONS = [
  { id: "B1", label: "Civil Documents" },
  { id: "B2", label: "Finances" },
  { id: "B3", label: "Education" },
  { id: "B4", label: "Employment" },
  { id: "B5", label: "Family" },
  { id: "B6", label: "Travel History" },
  { id: "B7", label: "Medical" },
  { id: "B8", label: "Readiness" },
  { id: "B9", label: "Final Details" },
];
